name = "fastapi"
compatibility_date = "2024-04-16"

[vars]
UPSTASH_REDIS_TOKEN = "AcZAASQgOTA2NTllOTgtYWQyOS00NDMxLWE0NmMtYTJiOWU5MDA3NWY3MzBjZmFjZDIyYzhiNDI3YWE3MWM5M2VjYmI2YTYyNGE="
UPSTASH_REDIS_URL = "https://unified-cheetah-50752.upstash.io"